### ISSUE TITLE
HtmlFormat.cs displays incorrect links when hosting service at custom path

### ISSUE THREAD

**Issue by EricMunn** [ServiceStack/Issues#580]
The changes made to resolve issue #541 appear to cause broken links when hosting a service in IIS at a custom path. 

For example, configuring the ServiceStack starter template to run from  **http://localhost:55479/CustomPath** :

A browser request to **http://localhost:55479/CustomPath/hello/Eric** displays links as **http://localhost:55479/CustomPath/CustomPath/hello/Eric**

In HttpRequestExtensions.cs/ResolveAbsoluteUrl, both the virtualPath and httpReq.RawUrl parameters contain the custom path - and the parameters appear to be incompletely merged in the downstream CombineWith().

Sample app at [https://github.com/EricMunn/ServiceStackBadCustomPath](https://github.com/EricMunn/ServiceStackBadCustomPath).  

As a workaround, I am currently following your suggestion in #541 to override ResolveAbsoluteUrl in my AppHost.

BTW, awesome product!  Thanks!

**Comment by mythz** [comment]
Thanks for the repro! This should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/93e46097219e1ad34b299dd96b6b293c328228e4).

This change is available from v5 that's now [available from MyGet](http://docs.servicestack.net/myget). Please review [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before upgrading.

**Comment by bzier** [comment]
Hi @mythz,

It looks like this issue is correctly resolved (using 5.0.2) when running a self-hosted app, or running through IIS Express. However, when hosting the application in full-blown IIS under a virtual directory, the problem persists.

Using @EricMunn's sample project, I changed the project properties to use 'Local IIS' and clicked 'Create Virtual Directory'. Browsing to the application is then done at the URL:
http://localhost/SSBadServiceUrl/CustomPath/hello/world
However, the resulting path on the ServiceStack HTML pages is the following:
http://localhost/SSBadServiceUrl/CustomPath/SSBadServiceUrl/CustomPath/hello/world

It is worth noting that when creating an IIS Site that points directly to the application folder (no virtual directory), the URL is correct. For example:
http://localhost:8050/CustomPath/hello/world

I believe it is just the virtual directory that is throwing things off. Please let me know if you need any more information. Thanks.

**Comment by mythz** [comment]
@bzier This should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/c4446d58e26a2485f91f96599a3c667030224d63

This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by bzier** [comment]
@mythz Excellent, thank you so much for the incredibly quick turn-around. I pulled the latest packages and verified that the problem is now resolved.
